variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_STRATEGY: fetch
  IMAGE_TAG_NAME: "${HARBOR_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"

stages:
  - build
  - gray
  # - stop_gray
  - production

build_image:
  stage: build
  image: docker:18.03
  variables:
    DOCKER_DRIVER: overlay
    DOCKER_HOST: tcp://docker:2375
    #GIT_SUBMODULES: init
    DOCKER_TLS_CERTDIR: "/certs"
  services:
    - name: docker:18.03-dind

  script:
    # - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@git.sysop.bigo.sg/".insteadOf "../../"  # for submodule
    # - git submodule sync && git submodule update --init  # for submodule
    - docker login "$HARBOR_REGISTRY" -u "$HARBOR_REGISTRY_USER" -p "$HARBOR_REGISTRY_PASSWORD"
    - docker build --pull -f docker/Dockerfile -t "$IMAGE_TAG_NAME" .
    - docker push "$IMAGE_TAG_NAME"
    - docker rmi "$IMAGE_TAG_NAME"

compiler_config:
  stage: build
  image: python:3.6
  script:
    - python -m pip install pyyaml
    - cd deploy && python generater.py
    - env | grep IMAGE
    - sed -i "s#__IMAGE__#${IMAGE_TAG_NAME}#" deploy-gray.yaml deploy-gray.yaml
    - sed -i "s#__IMAGE__#${IMAGE_TAG_NAME}#" deploy-production.yaml deploy-production.yaml

  artifacts:
    paths:
    - deploy/deploy-gray.yaml
    - deploy/deploy-production.yaml
    expire_in: 4 week

gray:
  stage: gray
  image: cnych/kubectl
  variables:
    GIT_STRATEGY: none
  environment:
    name: gray-sean
    # on_stop: stop_gray
  when: manual
  script:
    - kubectl config get-contexts
    - kubectl apply -f deploy/deploy-gray.yaml

# stop_gray:
#   image: cnych/kubectl
#   stage: stop_gray
#   variables:
#     GIT_STRATEGY: none
#   when: manual
#   environment:
#     name: gray-sean
#     action: stop
#   script:
#     - kubectl config get-contexts
#     - kubectl delete -f deploy/deploy-gray.yaml

deploy-hk:
  image: cnych/kubectl
  stage: production
  variables:
    GIT_STRATEGY: none
  script:
    - kubectl config get-contexts
    - kubectl apply -f deploy/deploy-production.yaml
  when: manual
