# auto-deploy namespace
apiVersion: v1
kind: Namespace
metadata:
  name: auto-deploy
  labels:
    app: auto-deploy
    istio-injection: enabled
  annotations:
    field.cattle.io/projectId: c-r89km:p-ltprd
---
# auto-deploy cgi deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-deploy-cgi
  namespace: auto-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auto-deploy-cgi
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: auto-deploy-cgi
        logging: "true"
    spec:
      containers:
      - name: auto-deploy-cgi
        image: __IMAGE__
        imagePullPolicy: Always
        resources:
          limits:
            # memory: "65536Mi"
            # cpu: "32000m"
        ports:
        - containerPort: 80
        command:
        - gunicorn
        - server:app
        - -b
        - 0.0.0.0:80
        - -w
        - "12"
        livenessProbe:
          httpGet:
            path: /auto-deploy/ping
            port: 80
          initialDelaySeconds: 120
          timeoutSeconds: 20
          periodSeconds: 10
        volumeMounts:
          - mountPath: /monitor/tools
            name: monitor-alarm
          - mountPath: /tmp
            name: monitor-alarm-tmp
      volumes:
        - name: monitor-alarm
          hostPath:
            path: /data/services/op_agent_d/tools
        - name: monitor-alarm-tmp
          hostPath:
            path: /tmp
      imagePullSecrets:
      - name: bigo-harbor-registry
---
# auto-deploy cgi service
apiVersion: v1
kind: Service
metadata:
  name: auto-deploy-cgi
  namespace: auto-deploy
spec:
  selector:
    app: auto-deploy-cgi
  ports:
  - name: http-auto-deploy-cgi
    port: 80
    targetPort: 80
  type: NodePort
---
# tf-serving model deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oilpaint-tf-serving
  namespace: auto-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oilpaint-tf-serving
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: oilpaint-tf-serving
    spec:
      containers:
      - name: oilpaint-tf-serving
        image: harbor.bigo.sg/bigo_ai/icpm/content/comics/models/tensorflow_serving_gpu_oilpaint_mmpro:latest
        imagePullPolicy: Always
        resources:
          limits:
            # memory: "65536Mi"
            # cpu: "32000m"
            nvidia.com/gpu: "1"
          requests:
            nvidia.com/gpu: "1"
        ports:
        - containerPort: 8500
      imagePullSecrets:
        - name: bigo-harbor-registry
---
# tf-serving model service
apiVersion: v1
kind: Service
metadata:
  name: oilpaint-tf-serving
  namespace: auto-deploy
spec:
  selector:
    app: oilpaint-tf-serving
  ports:
  - name: grpc-oilpaint-tf-serving
    port: 8500
    targetPort: 8500
  type: NodePort
---
# auto-deploy ingress
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: evg-ml.bigo.sg-auto-deploy
  namespace: auto-deploy
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: evg-ml.bigo.sg
    http:
      paths:
      - path: /auto-deploy
        backend:
          serviceName: auto-deploy-cgi
          servicePort: 80
